image: node:12.0.0

mochaTests: &mochaTests
  name: Run Mocha Tests
  caches:
    - node
  script:
    - npm ci
    - npm test

pipelines:
  branches:
    master:
      - step: *mochaTests

  pull-requests:
    "**":
      - step: *mochaTests
